create the displayMessage function
Suuuuha/christmas-wishes pull request #3
Opened 2017-09-08 16:31 UTC by mattlub

includes arduino setup using johnny-five module.

2017-09-08 16:38 UTC, Karyum requested changes
convert to es6

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +var five = require("johnny-five")
const here instead of var

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +var board = new five.Board({
also here

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +board.on("ready", function() {
arrow function here

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +  console.log('board ready')
remove this log

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +  var display = new five.Led.Matrix({
const

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +function displayMessage(display, message) {
arrow function

2017-09-08 16:38 UTC, Karyum commented on src/arduino/display_message.js
> +function displayLetters(display, letters) {
arrow function

2017-09-08 23:34 UTC, Karyum approved these changes
honestly i barely understand whats going on here but looks pretty pro :sweat_smile: :+1:

2017-09-09 08:42 UTC, mantagen approved these changes

2017-09-09 08:43 UTC, merged